version: "3.8"

services:
  mysqldb:
    image: mysql:latest
    # build:
    #   context: sql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: smarthome
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      # - mysql-data:/var/lib/mysql
      - ./sql-init:/docker-entrypoint-initdb.d/
    # networks:
    #   - node-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      retries: 10
      interval: 3s
      timeout: 30s


  frontend:
    image: node:14
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm start"
    depends_on:
      - user-management-backend
      - business-logic-backend

  user-management-backend:
    image: node:14
    working_dir: /app
    volumes:
      - ./user-management-backend:/app
    depends_on:
      - mysqldb
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=mysqldb
      - DB_USER=root
      - DB_PASSWORD=admin
      - DB_NAME=smarthome
      - DB_PORT=3306
    command: sh -c "npm install && npm start"

  business-logic-backend:
    image: node:14
    working_dir: /app
    volumes:
      - ./business-logic-backend:/app
    depends_on:
      - mysqldb
    ports:
      - "3002:3002"
    environment:
      - DB_HOST=mysqldb
      - DB_USER=root
      - DB_PASSWORD=admin
      - DB_NAME=smarthome
      - DB_PORT=3306
    command: sh -c "npm install && npm start"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - user-management-backend
      - business-logic-backend
